[project]
name = "marimo-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "marimo>=0.14.12",
  "pytest>=8.4.1",
]

[project.optional-dependencies]
test = ["pytest"]
